name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to be added'
        required: true
        type: string

jobs:
  release:
    uses: fizyk/actions-reuse/.github/workflows/shared-release.yml@custom-release
    with:
      version: ${{ github.event.inputs.version }}
